#!/bin/sh
# -*- sh -*-

# Parameters supported:       
#                             
# config                      
# autoconf                    
#                             
# Magic markers:              
#%# family=auto               
#%# capabilities=autoconf     

=head1 NAME                   
                              
elasticsearch_cache - A munin plugin that collects cache stats of your elasticsearch instances
                              
=head1 APPLICABLE SYSTEMS     
                              
elasticsearch                 
                              
=head1 CONFIGURATION          

None

=head1 BUGS

None known so far. If you find any, let me know.

=head1 AUTHOR

Tomas Doran (t0m) - c<< <bobtfish@bobtfish.net> >>
Kentaro Yoshida <y.ken.studio@gmail.com>

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "config" ]; then

        echo 'graph_title elasticsearch open files'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel number of open files'
        echo 'graph_category elasticsearch'
        echo 'used.label open files'
        echo 'used.type GAUGE'
        echo 'used.info The number of currently open files.'
        echo 'max.label max open files'
        echo 'max.type GAUGE'
        exit 0
fi


if [ -z "${es_user}" ]; then
  es_user="elasticsearch"
fi

PID=`ps -u $es_user -opid,comm | grep java | awk '{ print $1 }'`
VALUE=`ls /proc/$PID/fd/ | wc | awk '{ print $1 }'`
MAX_VALUE=`grep 'Max open files' /proc/$PID/limits | awk '{ print $5 }'`
echo "used.value $VALUE"
echo "max.value $MAX_VALUE"