#!/bin/sh
# -*- sh -*-

# AUTHOR: Moritz Onken <onken@netcubed.de>
# AUTHOR: Kentaro Yoshida <y.ken.studio@gmail.com>

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "config" ]; then

        echo 'graph_title elasticsearch translog size'
        echo 'graph_args --base 1024 -l 0'
        echo 'graph_vlabel size of translogs'
        echo 'graph_category elasticsearch'
        echo 'size.label size of translog files'
        echo 'size.type GAUGE'
        echo 'number.label number of translog files'
        echo 'number.type GAUGE'
        exit 0
fi

if [ -z "${es_user}" ]; then
  es_user="elasticsearch"
fi


if [ -n "${data_dir}" ]; then
    DIR=${data_dir}
else
    DIR=`ps -u $es_user -opid,command |tail -1| perl -ne 'print $1 if(/-Des.default.path.data=([\w\/]+)/)'`
fi

NUMBER=`ls $DIR/*/nodes/0/indices/*/*/translog/* | wc -l`
SIZE=`du -s $DIR/*/nodes/0/indices/*/*/translog/* | awk '{sum+=$1};END{print sum}'`
echo "number.value $NUMBER"
echo "size.value $SIZE"
