#!/usr/bin/env perl

# Parameters supported:
#
# config
# autoconf
#
# Magic markers:
#%# family=auto
#%# capabilities=autoconf

use strict;
use warnings;
use LWP;
use JSON qw/decode_json/;

=head1 NAME

elasticsearch_gc_time - A munin plugin that collects garbage collection time stats of your elasticsearch instances

=head1 APPLICABLE SYSTEMS

ElasticSearch

=head1 CONFIGURATION

None

=head1 BUGS

None known so far. If you find any, let me know.

=head1 AUTHOR

Timothy Messier (t0m) - c<< <tim.messier@gmail.com> >>
Kentaro Yoshida - https://github.com/y-ken

=cut

my %out = (young => 0, old => 0);
if ($ARGV[0] and $ARGV[0] eq 'config') {
    print "graph_title ElasticSearch gc time\n";
    print "graph_category elasticsearch\n";
    print "graph_vlabel miliseconds\n";

    foreach my $name (keys %out) {
        print "$name.label $name\n"."$name.type COUNTER\n";
    }
    exit(0);
}

my $host = exists $ENV{'host'} ? $ENV{'host'} : 'localhost';
my $port = exists $ENV{'port'} ? $ENV{'port'} : 9200;

my $ua = LWP::UserAgent->new;
$ua->timeout(10);

sub get_json_from_url {
    my $uri = shift;
    my $res = $ua->get($uri, 'Content-Type' => 'application/json' );
    my $data = {};
    if ($res->is_success) {
        $data = do { local $@; eval { decode_json($res->content) } };
    } elsif ($ENV{'MUNIN_DEBUG'}) {
        print STDERR "Error: ".$res->code." for $uri\n";
    }
    return $data;
}

my $data = get_json_from_url("http://$host:$port/_nodes/_local/stats/jvm");
if ( ! $data->{nodes} ) {
    foreach my $name (keys %out) {
        print "$name.value U\n";
    }
    exit(0);
}

foreach my $full_node_name (keys %{$data->{nodes}}) {
    next unless $data->{nodes}{$full_node_name};
    if (defined($data->{nodes}{$full_node_name}{jvm}{gc}{collectors}{young})) {
        $out{young} += $data->{nodes}{$full_node_name}{jvm}{gc}{collectors}{young}{collection_time_in_millis};
    }
    if (defined($data->{nodes}{$full_node_name}{jvm}{gc}{collectors}{old})) {
        $out{old} += $data->{nodes}{$full_node_name}{jvm}{gc}{collectors}{old}{collection_time_in_millis};
    }
}
foreach my $name (keys %out) {
    print "$name.value " . $out{$name} . "\n";
}
